name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request:
    types: [opened, labeled, reopened]

env:
  MY_GITHUB_TOKEN : ${{ secrets.GITHUB_PROJECT_TOKEN }}
  triage: Needs Triage 🔍

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Set Java project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'Java')
      env:
        project_nb: '25'
        org: 'microsoftgraph'
    - name: Set Go project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'Go')
      env:
        project_nb: '26'
        org: 'microsoftgraph'
    # - name: Set Ruby project info
    #   run: |
    #     echo '$PROJECT_NUMBER='$PROJECT_NB
    #     echo '$ORGANIZATION='$ORG
    #   if: contains(github.event.issue.labels.*.name, 'Ruby')
    #   env:
    #     project_nb: '6'
    #     org: 'microsoftgraph'
    - name: Set PHP project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'PHP')
      env:
        project_nb: '33'
        org: 'microsoftgraph'
    - name: Set Python project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'Python')
      env:
        project_nb: '34'
        org: 'microsoftgraph'
    - name: Set TypeScript project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'TypeScript')
      env:
        project_nb: '21'
        org: 'microsoftgraph'
    - name: Set CSharp project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'CSharp')
      env:
        project_nb: '28'
        org: 'microsoftgraph'
    - name: Set Generator project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'generator')
      env:
        project_nb: '220'
        org: 'microsoft'
    - name: Set Generator project info
      run: |
        echo '$PROJECT_NUMBER='$PROJECT_NB
        echo '$ORGANIZATION='$ORG
      if: contains(github.event.issue.labels.*.name, 'CLI')
      env:
        project_nb: '23'
        org: 'microsoftgraph'
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1.5.2
      with:
        app_id: ${{ secrets.GRAPHBOT_APP_ID }}
        private_key: ${{ secrets.GRAPHBOT_APP_PEM }}
    - name: Set token for assignment tasks
      run: echo '$MY_GITHUB_TOKEN=${{ steps.generate_token.outputs.token }}'
    - name: Assign issue to project
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: "${{ env.ORGANIZATION != '' }}"
      with:
        project: https://github.com/orgs/${{ env.ORGANIZATION }}/projects/${{ env.PROJECT_NUMBER }}
    - name: Set Triage
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: "${{ env.ORGANIZATION != '' }}"
      with:
        gh_token: ${{ env.MY_GITHUB_TOKEN }}
        organization: ${{ env.ORGANIZATION }}
        project_id: ${{ env.PROJECT_NUMBER }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.triage }}
